version: '3.8'

services:
  pump_fun_monitor:
    image: ghcr.io/markelz0r/pump_fun_monitor:latest
    container_name: pump_fun_monitor
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongo_user:itCHiAnTANiAtiveRClaRdw@mongodb:27017/your_database_name
    networks:
      - pump_network

  pump_fun_api:
    image: ghcr.io/markelz0r/pump_fun_api:latest
    container_name: pump_fun_api
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongo_user:itCHiAnTANiAtiveRClaRdw@mongodb:27017/your_database_name
    ports:
      - "3000:3000" # API now runs on port 3000
    networks:
      - pump_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: itCHiAnTANiAtiveRClaRdw
    ports:
      - "27017:27017" # Exposes MongoDB externally
    volumes:
      - mongo_data:/data/db
    networks:
      - pump_network

networks:
  pump_network:
    driver: bridge

volumes:
  mongo_data: