name: Deploy to MicroK8s

on:
  push:
    branches:
      - main  # Deploys on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      DOCKER_IMAGE: pump_fun_api  # Set this to your Docker image name

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker images
        run: |
          docker build -t ghcr.io/markelz0r/$DOCKER_IMAGE:latest -f Dockerfile .
          docker push ghcr.io/markelz0r/$DOCKER_IMAGE:latest